### ISSUE TITLE
Blind Reverse State Label

### ISSUE THREAD

**Issue by Rouzax** [Rouzax/Blinds#2]
# Blind Reverse State Label
If we take a Blind and enable Reverse State Label
![image](https://user-images.githubusercontent.com/4103090/194709173-40a09b83-0006-4b05-850e-3e0fdf2d2ab9.png)

**MQTT Config**
homeassistant/cover/Kantoor-Rolluik_Links/position_1/config
```json
{
    "command_topic": "zwave/Kantoor/Rolluik_Links/38/1/targetValue/set",
    "position_topic": "zwave/Kantoor/Rolluik_Links/38/1/currentValue",
    "set_position_topic": "zwave/Kantoor/Rolluik_Links/38/1/targetValue/set",
    "position_template": "{{ value_json.value | round(0) }}",
    "position_open": 99,
    "position_closed": 0,
    "payload_open": 99,
    "payload_close": 0,
    "device": {
        "identifiers": [
            "zwavejs2mqtt_0xc15d8aa6_node13"
        ],
        "manufacturer": "Fibargroup",
        "model": "Roller Shutter 3 (FGR223)",
        "name": "Kantoor-Rolluik Links",
        "sw_version": "5.1"
    },
    "name": "Kantoor - Rolluik Links - position_1",
    "unique_id": "zwavejs2mqtt_0xc15d8aa6_13-38-1-currentValue"
}
```

## Blind Open (Can not look out the window because State reverse)
![image](https://user-images.githubusercontent.com/4103090/194709244-5c1885ca-6807-4d06-8c06-e11d5931240b.png)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233303520,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Blind 75% (blind comes down a bit but majority of window still open)
![image](https://user-images.githubusercontent.com/4103090/194709268-abee919f-8ee7-41fc-86fc-d7e872d532b3.png)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233372867,
    "value": 74,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Press Open Blind button (will Close Blind as only labels are reversed)
![2022 10 08-15 16 44_Domoticz_-_LightSwitches_—_Mozilla_Firefox_lIEn8vymCH](https://user-images.githubusercontent.com/4103090/194709492-85e049d3-ee63-4387-bb81-56d8e5717603.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Press Close Blind button (will Open Blind as only labels are reversed)
![2022 10 08-15 14 39_Domoticz_-_LightSwitches_—_Mozilla_Firefox_wfhx4MHzor](https://user-images.githubusercontent.com/4103090/194709451-486c8ba4-0e58-4290-969e-69b666515c7e.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 98,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

Here we see the same issue as with the normal blind that we cannot reach 99 in zwaveJS as it will only send 98 as highest value from Domoticz to ZwaveJS.

## Slider from 10 to 0
This should fully close the Blind so Domoticz State should be open as State Labels are reversed, but something funny happens and instead of setting MQTT to 0 it sets it to 98 as the end of the slider marks `Open` and not 0, see the state label change while I slide.
Above screen is Domoticz, below is ZwaveJS

![2022 10 08-15 24 07_Z-Wave_JS_UI_—_Mozilla_Firefox_JQKVC2Lazx](https://user-images.githubusercontent.com/4103090/194709779-303a2a91-cf40-4022-8b9d-93451823652a.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 98,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Slider from 75 to 100
This should fully Open the Blind so Domoticz State should be Closed as State Labels are reversed, but something funny happens and instead of setting MQTT to 99 it sets it to 0 as the end of the slider marks `Closed` and not 99, see the state label change while I slide.
Above screen is Domoticz, below is ZwaveJS

![2022 10 08-15 32 27_Z-Wave_JS_UI_—_Mozilla_Firefox_6zaqEu3pHu](https://user-images.githubusercontent.com/4103090/194710150-faf4d35c-b557-4c56-91a7-258d444c01a8.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

**Comment by gizmocuz** [comment]
I just checked with a ESPHome blind sketch
When reverse state is on, pressing Open will (internally) close the blind and pressing Close will (internally) close the blind
This is the correct behaviour

Enabling only this option (without reverse position) only makes sense for blinds without percentage
This because open=100 and close is still 0
Thus, setting the slider to 75 will also actually send a value 75 to the blind

**Comment by Rouzax** [comment]
@gizmocuz Fixed
