### ISSUE TITLE
Blind Reverse State Label + Reverse Position

### ISSUE THREAD

**Issue by Rouzax** [Rouzax/Blinds#3]
# Blind Reverse State Label + Reverse Position
If we take a Blind and enable Reverse State Label and the Reverse Position
![image](https://user-images.githubusercontent.com/4103090/194710303-712e387d-ca79-43ea-8387-107c2b0676ab.png)

**MQTT Config**
homeassistant/cover/Kantoor-Rolluik_Links/position_1/config
```json
{
    "command_topic": "zwave/Kantoor/Rolluik_Links/38/1/targetValue/set",
    "position_topic": "zwave/Kantoor/Rolluik_Links/38/1/currentValue",
    "set_position_topic": "zwave/Kantoor/Rolluik_Links/38/1/targetValue/set",
    "position_template": "{{ value_json.value | round(0) }}",
    "position_open": 99,
    "position_closed": 0,
    "payload_open": 99,
    "payload_close": 0,
    "device": {
        "identifiers": [
            "zwavejs2mqtt_0xc15d8aa6_node13"
        ],
        "manufacturer": "Fibargroup",
        "model": "Roller Shutter 3 (FGR223)",
        "name": "Kantoor-Rolluik Links",
        "sw_version": "5.1"
    },
    "name": "Kantoor - Rolluik Links - position_1",
    "unique_id": "zwavejs2mqtt_0xc15d8aa6_13-38-1-currentValue"
}
```

## Blind Open (Can not look out the window because State reverse)
![image](https://user-images.githubusercontent.com/4103090/194710342-8f73f27d-333a-4d47-8176-19309d6b8989.png)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233303520,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Blind 75% (blind almost fully comes down of not much window left open)
![image](https://user-images.githubusercontent.com/4103090/194710404-7e46acd5-fd95-4d3c-961e-33ada58ab3f3.png)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233372867,
    "value": 25,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Press Open Blind button (will Close Blind as only labels are reversed)
![2022 10 08-15 40 08_Domoticz_-_LightSwitches_—_Mozilla_Firefox_CPT1kRfPX1](https://user-images.githubusercontent.com/4103090/194710437-0e6e59e1-f292-4fae-846b-00b4b7f40929.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Press Close Blind button (will Open Blind as only labels are reversed)
![2022 10 08-15 41 41_Domoticz_-_LightSwitches_—_Mozilla_Firefox_rmclTUmTwL](https://user-images.githubusercontent.com/4103090/194710515-dd8c71c1-1596-4942-a0ac-911293c8f5d5.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 98,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

Here we see the same issue as with the normal blind that we cannot reach 99 in zwaveJS as it will only send 1 as highest value from Domoticz to ZwaveJS.

## Slider from 10 to 0
This should fully Open the Blind so Domoticz State should be Closed as State Labels are reversed and the Slider.
Above screen is Domoticz, below is ZwaveJS
![2022 10 08-15 43 57_Z-Wave_JS_UI_—_Mozilla_Firefox_oR899bc72H](https://user-images.githubusercontent.com/4103090/194710608-bef28b2b-5d37-4be1-b719-c72db4856082.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 98,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Slider from 75 to 100
This should fully Close the Blind so Domoticz State should be Open as State Labels are reversed.
Above screen is Domoticz, below is ZwaveJS
![2022 10 08-15 49 16_Z-Wave_JS_UI_—_Mozilla_Firefox_HSwZKjbqT9](https://user-images.githubusercontent.com/4103090/194710813-94be1423-2706-4a9a-928d-3010a7853401.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

**Comment by gizmocuz** [comment]
Solved

**Comment by Rouzax** [comment]
@gizmocuz indeed al fixed
