### ISSUE TITLE
Blind Reverse Position

### ISSUE THREAD

**Issue by Rouzax** [Rouzax/Blinds#4]
# Blind Reverse Position
If we take a Blind and enable Reverse Position
![image](https://user-images.githubusercontent.com/4103090/194711002-775d6615-629a-445f-a750-3531f230d9ff.png)

**MQTT Config**
homeassistant/cover/Kantoor-Rolluik_Links/position_1/config
```json
{
    "command_topic": "zwave/Kantoor/Rolluik_Links/38/1/targetValue/set",
    "position_topic": "zwave/Kantoor/Rolluik_Links/38/1/currentValue",
    "set_position_topic": "zwave/Kantoor/Rolluik_Links/38/1/targetValue/set",
    "position_template": "{{ value_json.value | round(0) }}",
    "position_open": 99,
    "position_closed": 0,
    "payload_open": 99,
    "payload_close": 0,
    "device": {
        "identifiers": [
            "zwavejs2mqtt_0xc15d8aa6_node13"
        ],
        "manufacturer": "Fibargroup",
        "model": "Roller Shutter 3 (FGR223)",
        "name": "Kantoor-Rolluik Links",
        "sw_version": "5.1"
    },
    "name": "Kantoor - Rolluik Links - position_1",
    "unique_id": "zwavejs2mqtt_0xc15d8aa6_13-38-1-currentValue"
}
```

## Blind Open (Can look out the window, only slider is at 0 position)
![image](https://user-images.githubusercontent.com/4103090/194711057-89ee5b73-f9d7-49ff-a646-70af045d1c99.png)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233303520,
    "value": 99,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Blind 75% (blind almost fully comes down of not much window left open)
![image](https://user-images.githubusercontent.com/4103090/194711127-52227a77-75dc-421b-8615-773bc7bb6cce.png)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233372867,
    "value": 25,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Press Open Blind button
![2022 10 08-15 57 24_Domoticz_-_LightSwitches_—_Mozilla_Firefox_vLdEMPo8m6](https://user-images.githubusercontent.com/4103090/194711189-09ca6af6-4828-40a8-a5c3-8f0a62350a75.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 98,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

Here we see the same issue as with the normal blind that we cannot reach 99 in zwaveJS as it will only send 98 as highest value from Domoticz to ZwaveJS.

## Press Close Blind button
![2022 10 08-15 58 27_Domoticz_-_LightSwitches_—_Mozilla_Firefox_fwqI9tu151](https://user-images.githubusercontent.com/4103090/194711231-2bf8c583-6c3c-4d99-9be7-37fda686358d.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Slider from 10 to 0
This should fully Open the Blind so Domoticz State should be open, but something funny happens and instead of setting MQTT to 99 it sets it to 0 as the end of the slider marks `Closed` and not 0, see the state label change while I slide.
End result is Blind fully closed
Above screen is Domoticz, below is ZwaveJS
![2022 10 08-16 01 03_Z-Wave_JS_UI_—_Mozilla_Firefox_DBfHVYHmUD](https://user-images.githubusercontent.com/4103090/194711387-6d4cc4f7-6056-4d22-8045-792cb1ebfe35.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 0,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

## Slider from 75 to 100
This should fully Close the Blind so Domoticz State should be Closed, but something funny happens and instead of setting MQTT to 0 it sets it to 98 as the end of the slider marks `Closed` and not 0, see the state label change while I slide.
Above screen is Domoticz, below is ZwaveJS
![2022 10 08-16 02 50_Z-Wave_JS_UI_—_Mozilla_Firefox_MrePD5fLtL](https://user-images.githubusercontent.com/4103090/194711454-dc4251bb-cd4f-4bb8-a232-87ffa8e07ac4.gif)

**MQTT**
zwave/Kantoor/Rolluik_Links/38/1/currentValue
```json
{
    "time": 1665233665291,
    "value": 98,
    "nodeName": "Rolluik Links",
    "nodeLocation": "Kantoor"
}
```

**Comment by gizmocuz** [comment]
Solved

**Comment by Rouzax** [comment]
@gizmocuz Fixed
